### ISSUE TITLE
users-routes

### ISSUE THREAD

**Issue by aithmid** [L3iyanin/ft_transcendence#35]
add users routes containing:
***
### GET /users/:userId/info  ✅

response:
{
- full name
- username
- imgUrl
- number of friends wins, losses, and achievements

}
***
### GET /users/:userId/achievements  ✅

response:
{
list of all achievements (locked and unlocked) for the user  
}
***
### GET /users/:userId/friends  ✅

response:
{
- list of user friends' ids

}
***
### POST /users/:friendId/sendFriendRequest  ✅
***
### POST /users/:friendId/acceptFriendRequest  ✅
***
### POST /users/:friendId/block
***
### POST /users/:friendId/unblock
***
### GET /users/leaderboard ✅

response:
{
- return users indexed from 1 to n

}
***
### Get /users/:userId/friendRequests   ✅
***
### Put /users/profile/userName
***
### POST /users/profile/avatar (upload avatr image)

***
### POST /users/:friendId/discardFriendRequest   ✅

**Comment by benlyazid** [comment]
We have also to add 
**Get** /users/:friendId/friendRequest
**Put** /users/:userId/profile (update something in the profile)

**Comment by benlyazid** [comment]
Hi @twelve0  did you check if the user has already sent a friend Request it should not be sent again

**Comment by aithmid** [comment]
@benlyazid Yes done
